### ISSUE TITLE
Instagram slider fix

### ISSUE THREAD

**Issue by rdunning75** [calstatelaacm/Website18-19#3]

**Comment by EmilyPascua** [comment]
- Need new AccessKey after "Non-Square media" is unchecked.

**Comment by rdunning75** [comment]
@EmilyPascua if @pavitchawla doesn't respond to you, would it be possible to find the api on the web?

**Comment by rdunning75** [comment]
> @EmilyPascua if @pavitchawla doesn't respond to you, would i be possible to find the api on the web?
